name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache  # Docker layer caching
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache,mode=max  # Push cache

  deploy-to-ec2:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH private key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/testcrop_openssh
          chmod 600 ~/.ssh/testcrop_openssh

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user  # Or ubuntu for Ubuntu instances
          key: ~/.ssh/testcrop_openssh
          port: 22
          script: |
            # Stop any existing Docker containers (optional)
            docker stop my-container || true
            docker rm my-container || true
            
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest

            # Run the Docker container
            docker run -d --name my-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
