name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Run your test commands here, like `pytest` or `unittest`
          pytest tests/  # Adjust according to your test structure

  docker-build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache  # Docker layer caching
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache,mode=max  # Push cache

  deploy-to-ec2:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user  # Or ubuntu for Ubuntu instances
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop any existing Docker containers (optional)
            docker stop my-container || true
            docker rm my-container || true
            
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest

            # Run the Docker container
            docker run -d --name my-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
